// Package token provides secure opaque token generation and lookup hashing.
package token

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
)

const (
	defaultTokenBytes        = 32
	defaultRecoveryCodeBytes = 10
	minTokenBytes            = 16
	minLookupKeyBytes        = 32
	recoveryCodeGroupSize    = 4
)

var (
	// ErrInvalidLength reports an unsafe token byte length.
	ErrInvalidLength = errors.New("token: invalid length")

	// ErrEmptyToken reports that a token value was empty.
	ErrEmptyToken = errors.New("token: empty token")

	// ErrWeakLookupKey reports that an HMAC lookup key is too short.
	ErrWeakLookupKey = errors.New("token: weak lookup key")
)

// Generate returns a URL-safe opaque token with at least 128 bits of entropy.
func Generate(byteLength int) (string, error) {
	if byteLength < minTokenBytes {
		return "", errors.Join(ErrInvalidLength, fmt.Errorf("length must be at least %d bytes", minTokenBytes))
	}

	raw := make([]byte, byteLength)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}

	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// GenerateSessionID returns a URL-safe opaque session identifier.
func GenerateSessionID() (string, error) {
	return Generate(defaultTokenBytes)
}

// GenerateRefreshToken returns a URL-safe opaque refresh token.
func GenerateRefreshToken() (string, error) {
	return Generate(defaultTokenBytes)
}

// GenerateRecoveryCode returns a human-readable single-use recovery code.
func GenerateRecoveryCode() (string, error) {
	raw := make([]byte, defaultRecoveryCodeBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate recovery code: %w", err)
	}

	encoded := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(raw)
	return groupCode(encoded, recoveryCodeGroupSize), nil
}

// LookupHash returns a SHA-256 lookup hash for a high-entropy random token.
//
// This is appropriate for tokens generated by this package. Human passwords
// must use the password package instead.
func LookupHash(value string) ([]byte, error) {
	if value == "" {
		return nil, ErrEmptyToken
	}

	sum := sha256.Sum256([]byte(value))
	return sum[:], nil
}

// HMACLookupHash returns an HMAC-SHA-256 lookup hash for a high-entropy random
// token using an application-controlled lookup key.
func HMACLookupHash(value string, key []byte) ([]byte, error) {
	if value == "" {
		return nil, ErrEmptyToken
	}
	if len(key) < minLookupKeyBytes {
		return nil, errors.Join(ErrWeakLookupKey, fmt.Errorf("key must be at least %d bytes", minLookupKeyBytes))
	}

	mac := hmac.New(sha256.New, key)
	if _, err := mac.Write([]byte(value)); err != nil {
		return nil, fmt.Errorf("hash token: %w", err)
	}
	return mac.Sum(nil), nil
}

func groupCode(value string, size int) string {
	if value == "" {
		return ""
	}

	var groups []string
	for len(value) > size {
		groups = append(groups, value[:size])
		value = value[size:]
	}
	groups = append(groups, value)
	return strings.Join(groups, "-")
}
