// Package token provides secure opaque token generation and lookup hashing.
package token

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
)

const (
	defaultSecretBytes   = 32
	defaultPublicIDBytes = 16
	minTokenBytes        = 16

	// MinLookupKeyBytes is the minimum application-controlled HMAC key length
	// for token lookup hashes.
	MinLookupKeyBytes = 32
)

var (
	// ErrInvalidLength reports an unsafe token byte length.
	ErrInvalidLength = errors.New("token: invalid length")

	// ErrEmptyToken reports that a token value was empty.
	ErrEmptyToken = errors.New("token: empty token")

	// ErrWeakLookupKey reports that an HMAC lookup key is too short.
	ErrWeakLookupKey = errors.New("token: weak lookup key")
)

// GenerateOpaque returns a URL-safe opaque value with at least 128 bits of
// entropy.
func GenerateOpaque(byteLength int) (string, error) {
	if byteLength < minTokenBytes {
		return "", errors.Join(ErrInvalidLength, fmt.Errorf("length must be at least %d bytes", minTokenBytes))
	}

	raw := make([]byte, byteLength)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}

	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// GeneratePublicID returns a URL-safe public identifier.
func GeneratePublicID() (string, error) {
	return GenerateOpaque(defaultPublicIDBytes)
}

// GenerateAPIKeySecret returns a URL-safe opaque API key secret.
func GenerateAPIKeySecret() (string, error) {
	return GenerateOpaque(defaultSecretBytes)
}

// LookupHash returns a SHA-256 lookup hash for a high-entropy random token.
//
// This is appropriate for high-entropy API keys generated by this package. It
// is not suitable for human passwords.
func LookupHash(value string) ([]byte, error) {
	if value == "" {
		return nil, ErrEmptyToken
	}

	sum := sha256.Sum256([]byte(value))
	return sum[:], nil
}

// HMACLookupHash returns an HMAC-SHA-256 lookup hash for a high-entropy random
// token using an application-controlled lookup key.
func HMACLookupHash(value string, key []byte) ([]byte, error) {
	if value == "" {
		return nil, ErrEmptyToken
	}
	if len(key) < MinLookupKeyBytes {
		return nil, errors.Join(ErrWeakLookupKey, fmt.Errorf("key must be at least %d bytes", MinLookupKeyBytes))
	}

	mac := hmac.New(sha256.New, key)
	if _, err := mac.Write([]byte(value)); err != nil {
		return nil, fmt.Errorf("hash token: %w", err)
	}
	return mac.Sum(nil), nil
}
